# Generated by Django 5.2.9 on 2025-12-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_photo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='photo_profile',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]
